format = """
[](fg:#fafafa)\
$username\
$hostname\
[](fg:#fafafa)\
$os\
[>](fg:#4d2699)\
[](fg:#990026)\
$time\
$battery\
[](fg:#990026 bg:#007a9e)\
$directory\
[](fg:#007a9e)\
$nodejs\
$rust\
$golang\
$php\
$java\
$julia\
$ocaml\
$zig\
$lua\
$python\
$ruby\
$dart\
$c\
$git_branch\
$git_status\
$cmd_duration\
$status\
\n$character"""

[username]
style_user = "fg:#8a6408 bg:#fafafa"
style_root = "fg:#990026 bg:#fafafa"
format = "[ $user ]($style)"
show_always = true

[hostname]
style = "fg:#1a1a1a bg:#fafafa"
format = "[@$hostname ]($style)"
ssh_only = false

[directory]
style = "fg:#fafafa bg:#007a9e"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[os]
disabled = false
style = "fg:#4d2699"

[os.symbols]
AIX = "  "
ALTLinux = "  "
AOSC = "  "
AlmaLinux = "  "
Alpaquita = "  "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
Bluefin = "  "
CachyOS = "  "
CentOS = "  "
Debian = " 󰣚 "
DragonFly = "  "
Elementary = "  "
Emscripten = "  "
EndeavourOS = "  "
Fedora = " 󰣛 "
FreeBSD = "  "
Garuda = "  "
Gentoo = " 󰣨 "
HardenedBSD = " 󰞌 "
Illumos = "  "
InstantOS = "  "
Ios = " 󰀷 "
Kali = "  "
Linux = " 󰌽 "
Mabox = "  "
Macos = " 󰀵 "
Manjaro = "  "
Mariner = "  "
MidnightBSD = "  "
Mint = " 󰣭 "
NetBSD = "  "
NixOS = "  "
Nobara = "  "
OpenBSD = "  "
OpenCloudOS = "  "
OracleLinux = " 󰺡 "
PikaOS = "  "
Pop = "  "
Raspbian = " 󰐿 "
RedHatEnterprise = " 󱄛 "
Redhat = " 󱄛 "
Redox = " 󰀘 "
RockyLinux = "  "
SUSE = "  "
Solus = "  "
Ubuntu = " 󰕈 "
Ultramarine = "  "
Unknown = "  "
Uos = "  "
Void = "  "
Windows = " 󰍲 "
Zorin = "  "
openEuler = "  "
openSUSE = "  "


[git_branch]
symbol = ""
style = "fg:#1a1a1a"
format = "[>](fg:#1a1a1a)[[ $symbol $branch ](fg:#1a1a1a)]($style)"

[git_status]
style = "fg:#1a1a1a"
format = "[[($all_status$ahead_behind )](fg:#1a1a1a)]($style)"

[git_metrics]
disabled = true

[nodejs]
symbol = ""
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[ $symbol ($version) ](fg:#007a9e)]($style)"

[rust]
symbol = ""
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[ $symbol ($version) ](fg:#007a9e)]($style)"

[golang]
symbol = ""
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[ $symbol ($version) ](fg:#007a9e)]($style)"

[php]
symbol = ""
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[ $symbol ($version) ](fg:#007a9e)]($style)"

[java]
symbol = ""
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[ $symbol ($version) ](fg:#007a9e)]($style)"

[julia]
symbol = ""
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[ $symbol ($version) ](fg:#007a9e)]($style)"

[ocaml]
symbol = ""
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[ $symbol ($version) ](fg:#007a9e)]($style)"

[zig]
symbol = ""
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[ $symbol ($version) ](fg:#007a9e)]($style)"

[lua]
symbol = ""
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[ $symbol ($version) ](fg:#007a9e)]($style)"

[python]
symbol = ""
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[ $symbol ($version) ](fg:#007a9e)]($style)"

[ruby]
symbol = ""
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[ $symbol ($version) ](fg:#007a9e)]($style)"

[dart]
symbol = ""
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[ $symbol ($version) ](fg:#007a9e)]($style)"

[c]
symbol = "󰬊"
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[ $symbol ($version) ](fg:#007a9e)]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#990026"
format = "[[  $time ](fg:#fafafa bg:#990026)]($style)"

[cmd_duration]
min_time = 800
style = "fg:#007a9e"
format = "[>](fg:#007a9e)[[  $duration ](fg:#007a9e)]($style)"

[status]
disabled = false
style = "fg:#990026"
format = "[>](fg:#990026)[[ $status ](fg:#990026)]($style)"

[memory_usage]
disabled = true

[battery]
disabled = false
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
format = "[ $symbol $percentage ]($style)"

[[battery.display]]
threshold = 20
style = "bold fg:#fafafa bg:#990026"

[[battery.display]]
threshold = 100
style = "fg:#8a6408 bg:#990026"

[character]
success_symbol = "[>](bold #007a28)"
error_symbol = "[>](bold #990026)"
